name: "Build with Cargo"
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          
      - uses: actions-rs/toolchain@v1
        name: Install rust toolchain
        with:
          toolchain: nightly
          override: true

      - uses: Swatinem/rust-cache@v2
        name: Add caching

      - run: nix develop .?submodules=1#anyrun --command cargo build --verbose
        name: Build crate
