name: "Update repository dependencies"

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 4 1 * *"

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
                  
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Bump nix
        run: nix flake update

      - name: Bump rust
        run: nix shell nixpkgs#cargo --command cargo update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: "${{ secrets.github_token }}"
          title: "chore: update all inputs"
          author: GitHub <noreply@github.com>
          branch: automated-dep-updates
          branch-suffix: timestamp
          delete-branch: true
          commit-message: |
            chore: update all inputs

            Co-authored-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
