name: "Check flake"

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: 
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - install.sh
      - screenshots/**
      - examples/**
      - docs/**
      
  pull_request:
    branches:
      - master

jobs:
  check-nix:
    name: "nix flake check"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          
      - name: Check Flake
        run: nix flake check .?submodules=1#
      
