name: Rust CI

on:
  push:
    branches:
      - master
      - '**/feature/*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup dependencies
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libgtk-layer-shell-dev

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v2
        name: Add caching

      - name: Install dependencies
        run: cargo fetch

      - name: Build
        run: cargo build --release

      - name: Run tests
        run: cargo test --verbose

  clippy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup dependencies
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libgtk-layer-shell-dev

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - uses: Swatinem/rust-cache@v2
        name: Add caching

      - name: Install Clippy
        run: rustup component add clippy

      - name: Run Clippy
        run: cargo clippy --all-targets -- --deny warnings -A clippy::invisible_characters

  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Rustfmt
        run: rustup component add rustfmt

      - name: Check Rustfmt
        run: cargo fmt -- --check
